# Generated by Django 5.0.6 on 2024-05-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dias',
            old_name='descrição',
            new_name='descricao',
        ),
        migrations.AddField(
            model_name='dias',
            name='topicos',
            field=models.CharField(blank=True, max_length=1000000000, null=True),
        ),
    ]
