# Generated by Django 5.0.6 on 2024-05-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dias', '0002_rename_descrição_dias_descricao_dias_topicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dias',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
